services:
  shop-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  shop:
    build: .
    restart: always
    depends_on:
      shop-db:
        condition: service_healthy
    ports:
      - "1111:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shop-db:3306/shop
      SPRING_DATASOURCE_USERNAME: shop
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
