#version: "3.9"
#services:
#  servlet:
#    build: .
#    ports:
#      - "1111:8080"
#    depends_on:
#      - shopDB
#  shopDB:
#    image: "mysql"
#    ports:
#      - "3306:3306"
#    environment:
#        MYSQL_ROOT_PASSWORD: 1234

#version: '3.8'
#
#services:
#  shop-app:
#    build: .
#    container_name: shop
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopDB
#      SPRING_DATASOURCE_USERNAME: shop
#      SPRING_DATASOURCE_PASSWORD: 1234
#
#  db:
#    image: mysql:8
#    container_name: shop-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: shopDB
#    ports:
#      - "3306:3306"


services:
  shop-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  shop:
    build: .
    restart: always
    depends_on:
      shop-db:
        condition: service_healthy
    ports:
      - "1111:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shop-db:3306/shop
      SPRING_DATASOURCE_USERNAME: shop
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
