<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
</head>
<body>

<header>
</header>
<h1>Shop Flip-Flop</h1><hr>

<h2>Log in:</h2>
<form action="/login" method="post">
    Email: <input name="username" type="email"> <br>
    Password: <input name="password" type="password"> <br>

<#--    <input type="hidden" value="_csrf">-->
    <input type="submit" value="Enter">
</form>

<hr>
<a href="/registration">Registration</a>

</body>
</html>
